# Generated by Django 5.0.7 on 2024-07-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blibliotecario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.CharField(max_length=100)),
                ('data_devolucao', models.CharField(max_length=100)),
                ('leitor', models.CharField(max_length=11)),
                ('livro', models.CharField(max_length=11)),
                ('bibliotecario', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='leitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('ano_publicacao', models.CharField(max_length=100)),
                ('editora', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=40)),
            ],
        ),
    ]
