# Generated by Django 5.0.7 on 2024-07-15 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='bibliotecario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emprestimo.blibliotecario'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='leitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emprestimo.leitor'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emprestimo.livro'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emprestimo.categoria'),
        ),
    ]
